---
- name: install java on ubuntu
  hosts: all
  become: yes
  tasks: 
    - name: Install Apache on Ubuntu Server
      ansible.builtin.apt:
        name: openjdk-11-jdk
        state: present  
      when: ansible_os_family == "Debian"
    - name: Install Apache on CentOS Server
      ansible.builtin.yum:
        name: java-11-openjdk-devel
        state: present  
      when: ansible_os_family == "RedHat"  